### ISSUE TITLE
Stopped working with new snapshots release

### ISSUE THREAD

**Issue by sojusnik** [gesellkammer/zim-plugins#6]
As with `0.74.0-SNAPSHOT-t202109171459~ubuntu21.04.1` from [Jaap's PPA](https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots?field.series_filter=hirsute) the tag autocompletion plugin stopped working.

Can you have a look on this?

**Comment by gesellkammer** [comment]
I have 0.74 working via github and "python setup.py install" and the plugin is working fine (also on ubuntu 21.04)

**Comment by sojusnik** [comment]
It worked with the new stable release from the [master PPA](https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim?field.series_filter=hirsute), but after the last [snapshots release](https://launchpad.net/~jaap.karssenberg/+archive/ubuntu/zim-snapshots?field.series_filter=hirsute) it stopped working.

This is what I'm getting when typing `@`:

```
$ zim -D
DEBUG: Loading config from: <ConfigFile: /home/sojusnik/.config/zim/preferences.conf>
DEBUG: New extendable: <zim.plugins.InsertedObjectTypeMap object at 0x7fbd0f1f8af0>
DEBUG: Loading plugin: printtobrowser
DEBUG: Loading plugin: tableeditor
DEBUG: Load extension: <class 'zim.plugins.tableeditor.TableViewObjectType'>
DEBUG: register_object: "table"
DEBUG: Loading plugin: versioncontrol
DEBUG: Loading plugin: tableofcontents
DEBUG: Loading plugin: bookmarksbar
DEBUG: Loading plugin: spell
DEBUG: Loading plugin: zim-zotero-plugin
DEBUG: Loading plugin: insertsymbol
DEBUG: Loading plugin: pathbar
DEBUG: Loading plugin: backlinkpane
DEBUG: Loading plugin: tags
DEBUG: Loading plugin: linkmap
DEBUG: Loading plugin: attachmentbrowser
DEBUG: Loading plugin: distractionfree
DEBUG: Loading plugin: copy-rich
DEBUG: Loading plugin: linesorter
DEBUG: Loading plugin: commandpalette
DEBUG: Loading plugin: tagcomplete
INFO: This is zim 0.74.0
DEBUG: Python version is sys.version_info(major=3, minor=9, micro=5, releaselevel='final', serial=0)
DEBUG: Platform is posix
DEBUG: Not running from a source dir
DEBUG: Set XDG_DATA_HOME to /home/sojusnik/.local/share
DEBUG: Set XDG_DATA_DIRS to [<Dir: /usr/share/gnome-xorg>, <Dir: /home/sojusnik/.local/share/flatpak/exports/share>, <Dir: /var/lib/flatpak/exports/share>, <Dir: /usr/local/share>, <Dir: /usr/share>]
DEBUG: Set XDG_CONFIG_HOME to /home/sojusnik/.config
DEBUG: Set XDG_CONFIG_DIRS to [<Dir: /etc/xdg/xdg-gnome-xorg>, <Dir: /etc/xdg>]
DEBUG: Set XDG_CACHE_HOME to /home/sojusnik/.cache
DEBUG: Connecting to /run/user/1000/zim-0.74.0-e63203e4
DEBUG: Got error in dispatch: No such file or directory
DEBUG: Starting primary process
DEBUG: Start listening on: /run/user/1000/zim-0.74.0-e63203e4
DEBUG: Loading config from: <zim.notebook.info.VirtualFile object at 0x7fbd06ef64f0>
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/notebook.zim
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/notebook.zim
DEBUG: Connecting to database file: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/.zim/index.db
DEBUG: Loading config from: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/.zim/state.conf
DEBUG: New extendable: <Notebook: Allgemeines>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlNotebookExtension'>
INFO: VCS detected: git - /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines
DEBUG: Loading config from: <ConfigFile: /home/sojusnik/.config/zim/style.conf>
DEBUG: Autosave interval: 10 - use threads: True
INFO: Page changed on disk: Entwürfe
INFO: Open page: Entwürfe (Entwürfe)
DEBUG: New extendable: <notebookview.NotebookView object at 0x7fbd06ecbf00 (zim+gui+notebookview+NotebookView at 0x26c9ae0)>
DEBUG: Load extension: <class 'zim.plugins.attachmentbrowser.AttachmentBrowserWindowExtension'>
DEBUG: Action: toggle_panes(False)
DEBUG: Action: toggle_panes(True)
DEBUG: Load extension: <class 'zim.plugins.backlinkpane.BackLinksPanePageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.insertsymbol.InsertSymbolPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.linesorter.LineSorterPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.linkmap.LinkMapPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.printtobrowser.PrintToBrowserPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.spell.SpellPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tableofcontents.ToCPageViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.tags.TagsNotebookViewExtension'>
DEBUG: Load extension: <class 'zim.plugins.zim-zotero-plugin.ZoteroPageViewExtension'>
DEBUG: New extendable: <mainwindow.MainWindow object at 0x7fbd06f057c0 (zim+gui+mainwindow+MainWindow at 0x264a500)>
DEBUG: Load extension: <class 'zim.plugins.bookmarksbar.BookmarksBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.commandpalette.CommandPaletteMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.copy-rich.RichCopyWindow'>
DEBUG: Load extension: <class 'zim.plugins.distractionfree.DistractionFreeMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.pathbar.PathBarMainWindowExtension'>
DEBUG: Load extension: <class 'zim.plugins.tagcomplete.TagAutocompleteWin'>
DEBUG: Load extension: <class 'zim.plugins.versioncontrol.VersionControlMainWindowExtension'>
INFO: Running: ('git', 'status', '--porcelain') (cwd: '/home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines')
DEBUG: No autosave version needed - no changes
DEBUG: Accelmap: /home/sojusnik/.config/zim/accelmap
DEBUG: Add window: MainWindow
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
DEBUG: BackgroundCheck started
DEBUG: BackgroundCheck finished
Traceback (most recent call last):
  File "/home/sojusnik/.local/share/zim/plugins/tagcomplete.py", line 87, in on_key_press_event
    self.tag_auto_completion()
  File "/usr/lib/python3/dist-packages/zim/actions.py", line 130, in __call__
    return self._action.func(self._instance, *args, **kwargs)
  File "/home/sojusnik/.local/share/zim/plugins/tagcomplete.py", line 83, in tag_auto_completion
    tag_auto_completion.completion(tag_list)
  File "/home/sojusnik/.local/share/zim/plugins/tagcomplete.py", line 198, in completion
    self.ac_tree_view.completion_win.show_all()
  File "/usr/lib/python3/dist-packages/zim/gui/widgets.py", line 2770, in show_all
    self.init_uistate()
  File "/usr/lib/python3/dist-packages/zim/gui/widgets.py", line 2579, in init_uistate
    self.uistate.define((
AttributeError: 'Window' object has no attribute 'uistate'
DEBUG: Store page in background: Entwürfe
DEBUG: Index file: /home/sojusnik/Sonstiges/Zim Notebooks/Allgemeines/Entwürfe.txt
^CERROR: KeyboardInterrupt
```

**Comment by gesellkammer** [comment]
This works with git master.

**Comment by sojusnik** [comment]
Try git [develop](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commits/develop) and you'll reproduce it. [Master](https://github.com/zim-desktop-wiki/zim-desktop-wiki/commits/master) doesn't have recent fixes.
